version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8889:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "APP_URL=http://web"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=tools"
            - "MYSQL_DATABASE=lvue"
        ports:
            - "33069:3306"

